### ISSUE TITLE
LZW Encoder issue

### ISSUE THREAD

**Issue by NickeManarin** [lilith/GifLib#1]
Hi, It seems that your LZW encoder does not work with a CodeSize less than 8 bits.

**Comment by lilith** [comment]
Don't use this! It's marked [ignore]

**Comment by NickeManarin** [comment]
Oh, I didn't notice it. Okay...
[The original project on Codeplex has the same code. It is unmodified]

But still, all of the LZW encoders out there only work with 8bits. Did you find any other that can accept less bits?
